### ISSUE TITLE
Complex expressions doesn't work

### ISSUE THREAD

**Issue by aiboy** [lahmatiy/jora#4]
This one works
```
jora package.json '(.dependencies.keys()-.devDependencies.keys())'

[ 'clap', 'jison', 'really-relaxed-json' ]
```

And this one doesn't
```
jora package.json '(.devDependencies.keys() - (.dependencies.keys() - .devDependencies.keys())'

/Users/ayuokhrimenko/Sites/jora/bin/jora:33
    throw e;
    ^

Error: Parse error on line 1:
...Dependencies.keys())
-----------------------^
Expecting ')', 'IN', 'NOTIN', 'AND', 'OR', '?', '+', '-', '*', '/', '%', '=', '!=', '<', '<=', '>', '>=', '~=', got 'EOF'
    at Parser.parseError (eval at createParser (/Users/ayuokhrimenko/Sites/jora/node_modules/jison/lib/jison.js:1327:13), <anonymous>:222:21)
    at Parser.parse (eval at createParser (/Users/ayuokhrimenko/Sites/jora/node_modules/jison/lib/jison.js:1327:13), <anonymous>:289:22)
    at compileFunction (/Users/ayuokhrimenko/Sites/jora/src/index.js:350:23)
    at createQuery (/Users/ayuokhrimenko/Sites/jora/src/index.js:385:37)
    at Command.action_ (/Users/ayuokhrimenko/Sites/jora/bin/jora:15:27)
    at Command.run (/Users/ayuokhrimenko/Sites/jora/node_modules/clap/index.js:747:22)
    at Object.<anonymous> (/Users/ayuokhrimenko/Sites/jora/bin/jora:24:13)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

**Comment by lahmatiy** [comment]
You're missing closing parenthesis in the query

**Comment by aiboy** [comment]
My bad.  This one works
```jora package.json '(.devDependencies.keys() - (.dependencies.keys() - .devDependencies.keys()))'```
